export const STATUS_LOADING = 'STATUS_LOADING';
export const STATUS_LOADED = 'STATUS_LOADED';
export const USER_STATUS_APPLIED = 'USER_STATUS_APPLIED';
export const USER_STATUS_INTERVIEWED = 'USER_STATUS_INTERVIEWED';
export const USER_STATUS_HIRED = 'USER_STATUS_HIRED';